# Generated by Django 5.1.2 on 2024-11-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskattachment",
            name="file",
            field=models.ImageField(upload_to="task-attachments/%Y-%m-%d/", verbose_name="Task Photo"),
        ),
    ]
