# Generated by Django 5.1.2 on 2024-11-06 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_taskattachment_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskattachment",
            old_name="file",
            new_name="image",
        ),
    ]
