# Generated by Django 5.1.2 on 2024-10-24 12:14

import django.db.models.deletion
import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        storage=django_minio_backend.models.MinioBackend(bucket_name="django-media-files-bucket"),
                        upload_to=django_minio_backend.models.iso_date_prefix,
                        verbose_name="Task Photo",
                    ),
                ),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.task")),
            ],
        ),
    ]
