# Generated by Django 5.1.1 on 2024-10-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_comment_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.task")),
            ],
        ),
    ]
