# Generated by Django 5.1.2 on 2024-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_rename_file_taskattachment_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskattachment",
            name="image",
        ),
        migrations.AddField(
            model_name="taskattachment",
            name="file",
            field=models.FileField(default=0, upload_to="task-attachments/%Y-%m-%d/", verbose_name="Task Attachment"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskattachment",
            name="status",
            field=models.CharField(default="pending"),
        ),
    ]
