# Generated by Django 5.1.2 on 2024-11-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_remove_taskattachment_image_taskattachment_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattachment",
            name="file_upload_url",
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
