# Generated by Django 5.1.1 on 2024-10-11 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_timelog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timelog",
            name="end_time",
        ),
    ]
