# Generated by Django 5.1.1 on 2024-10-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_remove_timelog_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelog",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
