services:
  app:
    image: ebs-milestone-2
    build: .
    environment:
      - DEBUG=true
      - DATABASE_URL=postgres://postgres:postgres@postgres-db:5432/postgres
    ports:
      - "8000:8000"
    # tty: true
    # entrypoint: bash
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
