services:
  app:
    image: ebs-milestone-2
    build: .
    environment:
      - DEBUG=true
      - DB_HOST=postgres-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - CELERY_BROKER_USER=admin
      - CELERY_BROKER_PASSWORD=admin
      - CELERY_BROKER_HOST=rabbitmq-broker
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    volumes:
      - ./fixtures:/app/fixtures
#    tty: true
#    entrypoint: bash
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command: >
      postgres -c shared_preload_libraries=pg_stat_statements
    volumes:
      - ./postgres://docker-entrypoint-initdb.d
  pg-hero:
    image: ankane/pghero:latest
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres-db:5432/postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    tty: true
  redis-db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./local/db-data/redis-db:/data/redis
  mailhog-mock:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  rabbitmq-broker:
    image: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin