name: Django CI

on: [pull_request, push]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff Format
        run: ruff format .
      - name: Run Ruff Check and Fix
        run: ruff check . --fix
      - name: Commit Files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Apply Ruff fixes" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
  test:
    needs: ruff-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
      - name: Execute tests in the running services
        run: docker compose exec app python manage.py test
