name: Django CI

on: [pull_request]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Ruff Lint
        uses: astral-sh/ruff-action@v1
  test:
    needs: ruff-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
      - name: Execute tests in the running services
        run: docker compose exec app python manage.py test
